-- MySQL Script generated by MySQL Workbench
-- 04/08/16 16:51:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tempofthingsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tempofthingsdb` ;

-- -----------------------------------------------------
-- Schema tempofthingsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tempofthingsdb` DEFAULT CHARACTER SET utf8 ;
USE `tempofthingsdb` ;

-- -----------------------------------------------------
-- Table `tempofthingsdb`.`sensor1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tempofthingsdb`.`sensor1` ;

CREATE TABLE IF NOT EXISTS `tempofthingsdb`.`sensor1` (
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `temperature` FLOAT NOT NULL,
  PRIMARY KEY (`timestamp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tempofthingsdb`.`sensor2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tempofthingsdb`.`sensor2` ;

CREATE TABLE IF NOT EXISTS `tempofthingsdb`.`sensor2` (
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `temperature` FLOAT NOT NULL,
  PRIMARY KEY (`timestamp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
